controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_steering_controller:
      type: position_controllers/JointGroupPositionController

    right_steering_controller:
      type: position_controllers/JointGroupPositionController

    left_front_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_rear_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_rear_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters: {}

left_steering_controller:
  ros__parameters:
    joints:
      - left_steering_hinge_joint
    pid:
      p: 35.0
      i: 0.0
      d: 5.0

right_steering_controller:
  ros__parameters:
    joints:
      - right_steering_hinge_joint
    pid:
      p: 35.0
      i: 0.0
      d: 5.0

left_front_wheel_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
    pid:
      p: 10
      i: 1.0
      d: 0.0
      i_clamp: 5.0

right_front_wheel_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint
    pid:
      p: 10
      i: 1.0
      d: 0.0
      i_clamp: 5.0

left_rear_wheel_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
    pid:
      p: 10
      i: 1.0
      d: 0.0
      i_clamp: 5.0

right_rear_wheel_controller:
  ros__parameters:
    joints:
      - rear_right_wheel_joint
    pid:
      p: 10
      i: 1.0
      d: 0.0
      i_clamp: 5.0 